/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DecisionBriefsRouteImport } from './routes/decision-briefs'
import { Route as NewScenarioRouteImport } from './routes/new-scenario'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RiskCentreRouteImport } from './routes/risk-centre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionBriefsRoute = DecisionBriefsRouteImport.update({
  id: '/decision-briefs',
  path: '/decision-briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewScenarioRoute = NewScenarioRouteImport.update({
  id: '/new-scenario',
  path: '/new-scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskCentreRoute = RiskCentreRouteImport.update({
  id: '/risk-centre',
  path: '/risk-centre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/decision-briefs': typeof DecisionBriefsRoute
  '/new-scenario': typeof NewScenarioRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/risk-centre': typeof RiskCentreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/decision-briefs': typeof DecisionBriefsRoute
  '/new-scenario': typeof NewScenarioRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/risk-centre': typeof RiskCentreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/decision-briefs': typeof DecisionBriefsRoute
  '/new-scenario': typeof NewScenarioRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/risk-centre': typeof RiskCentreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/data-sources'
    | '/decision-briefs'
    | '/new-scenario'
    | '/profile'
    | '/recommendations'
    | '/risk-centre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/data-sources'
    | '/decision-briefs'
    | '/new-scenario'
    | '/profile'
    | '/recommendations'
    | '/risk-centre'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/data-sources'
    | '/decision-briefs'
    | '/new-scenario'
    | '/profile'
    | '/recommendations'
    | '/risk-centre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DecisionBriefsRoute: typeof DecisionBriefsRoute
  NewScenarioRoute: typeof NewScenarioRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RiskCentreRoute: typeof RiskCentreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-briefs': {
      id: '/decision-briefs'
      path: '/decision-briefs'
      fullPath: '/decision-briefs'
      preLoaderRoute: typeof DecisionBriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-scenario': {
      id: '/new-scenario'
      path: '/new-scenario'
      fullPath: '/new-scenario'
      preLoaderRoute: typeof NewScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-centre': {
      id: '/risk-centre'
      path: '/risk-centre'
      fullPath: '/risk-centre'
      preLoaderRoute: typeof RiskCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DataSourcesRoute: DataSourcesRoute,
  DecisionBriefsRoute: DecisionBriefsRoute,
  NewScenarioRoute: NewScenarioRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  RiskCentreRoute: RiskCentreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
